name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin_ext: ""
          - target: x86_64-apple-darwin
            os: macos-13
            bin_ext: ""
          - target: aarch64-apple-darwin
            os: macos-14
            bin_ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin_ext: ".exe"
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install musl dependencies
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package binary
        run: |
          BIN_NAME=rngo
          OUT=dist/${BIN_NAME}-${{ matrix.target }}${{ matrix.bin_ext }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/$BIN_NAME${{ matrix.bin_ext }} $OUT
          cd dist
          zip ${BIN_NAME}-${{ matrix.target }}.zip ${BIN_NAME}-${{ matrix.target }}${{ matrix.bin_ext }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
